/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
/**
 * A collection of constants used by the "demo" ONC/RPC program.
 */
public class demo {
    public const int cat_2 = 42;
    public const int test_2 = 100;
    public const int mult_2 = 71;
    public const int llcat_2 = 55;
    public const int SECOND_DEMO_VERSION = 2;
    public const int test_marshal_2 = 121;
    public const int FIRST_DEMO_VERSION = 1;
    public const int FIXEDBUFFERLENGTH = 64;
    public const int concat_1 = 2;
    public const int readSomeResult_1 = 42;
    public const int checkfoo_2 = 3;
    public const int DEMO = 0x20049678;
    public const int cat3_2 = 43;
    public const int checkfoo_1 = 3;
    public const int NULL_1 = 0;
    public const int ll_1 = 5;
    public const int C_C = 42;
    public const int C_A = C_C;
    public const int C_B = C_A;
    public const int NULL_2 = 0;
    public const int foo_1 = 4;
    public const int echo_1 = 1;
}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of demo.cs
