/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
/**
 * Enumeration (collection of constants).
 */
public class ENUMFOO {

    public const int FOO = 0;
    public const int BAR = 0+1;
    public const int BAZ_1 = demo.C_B;
    public const int BAZ_2 = demo.C_B+1;
    public const int BAZ_3 = ENUMBAZ.E_BAZ;

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of ENUMFOO.cs
