/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
/**
 * Enumeration (collection of constants).
 */
public class ENUMBAZ {

    public const int E_BAZ = demo.C_B;

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of ENUMBAZ.cs
