/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
using global::org.acplt.oncrpc;

public class LINKEDLIST : XdrAble {
    public int foo;
    public LINKEDLIST next;

    public LINKEDLIST() {
    }

    public LINKEDLIST(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        LINKEDLIST _this = this;
        do {
            xdr.xdrEncodeInt(_this.foo);
            _this = _this.next;
            xdr.xdrEncodeBoolean(_this != null);
        } while ( _this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        LINKEDLIST _this = this;
        LINKEDLIST _next;
        do {
            _this.foo = xdr.xdrDecodeInt();
            _next = xdr.xdrDecodeBoolean() ? new LINKEDLIST() : null;
            _this.next = _next;
            _this = _next;
        } while ( _this != null );
    }

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of LINKEDLIST.cs
