/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
using global::org.acplt.oncrpc;

public class SILLYSTRUCT : XdrAble {
    public byte [] fixedbuffer;
    public byte [] buffer;
    public byte [] fixedbytes;
    public byte [] bytes;
    public int ui1;
    public int ui2;
    public string nonsense;

    public SILLYSTRUCT() {
    }

    public SILLYSTRUCT(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeByteFixedVector(fixedbuffer, 512);
        xdr.xdrEncodeByteVector(buffer);
        xdr.xdrEncodeOpaque(fixedbytes, demo.FIXEDBUFFERLENGTH);
        xdr.xdrEncodeDynamicOpaque(bytes);
        xdr.xdrEncodeInt(ui1);
        xdr.xdrEncodeInt(ui2);
        xdr.xdrEncodeString(nonsense);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fixedbuffer = xdr.xdrDecodeByteFixedVector(512);
        buffer = xdr.xdrDecodeByteVector();
        fixedbytes = xdr.xdrDecodeOpaque(demo.FIXEDBUFFERLENGTH);
        bytes = xdr.xdrDecodeDynamicOpaque();
        ui1 = xdr.xdrDecodeInt();
        ui2 = xdr.xdrDecodeInt();
        nonsense = xdr.xdrDecodeString();
    }

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of SILLYSTRUCT.cs
