/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
using global::org.acplt.oncrpc;

public class STRINGVECTOR : XdrAble {

    public STRING [] value;

    public STRINGVECTOR() {
    }

    public STRINGVECTOR(STRING [] value) {
        this.value = value;
    }

    public STRINGVECTOR(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        { int _size = value.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { value[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        { int _size = xdr.xdrDecodeInt(); value = new STRING[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { value[_idx] = new STRING(xdr); } }
    }

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of STRINGVECTOR.cs
