/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
using global::org.acplt.oncrpc;

public class TREE : XdrAble {
    public string key;
    public string value;
    public TREE left;
    public TREE right;

    public TREE() {
    }

    public TREE(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        TREE _this = this;
        do {
            xdr.xdrEncodeString(_this.key);
            xdr.xdrEncodeString(_this.value);
            if ( _this.left != null ) { xdr.xdrEncodeBoolean(true); _this.left.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
            _this = _this.right;
            xdr.xdrEncodeBoolean(_this != null);
        } while ( _this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        TREE _this = this;
        TREE _next;
        do {
            _this.key = xdr.xdrDecodeString();
            _this.value = xdr.xdrDecodeString();
            _this.left = xdr.xdrDecodeBoolean() ? new TREE(xdr) : null;
            _next = xdr.xdrDecodeBoolean() ? new TREE() : null;
            _this.right = _next;
            _this = _next;
        } while ( _this != null );
    }

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of TREE.cs
