/*
 * Automatically generated by jrpcgen 1.0.7 on 2021/9/14
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace tests.org.acplt.oncrpc.jrpcgen{
using global::org.acplt.oncrpc;

public class UNION : XdrAble {
    public bool okay;
    public LINKEDLIST list;

    public UNION() {
    }

    public UNION(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(okay);
        if ( okay == true ) {
            if ( list != null ) { xdr.xdrEncodeBoolean(true); list.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        okay = xdr.xdrDecodeBoolean();
        if ( okay == true ) {
            list = xdr.xdrDecodeBoolean() ? new LINKEDLIST(xdr) : null;
        }
    }

}
} //End of Namespace tests.org.acplt.oncrpc.jrpcgen
// End of UNION.cs
